# Generated by Django 5.2.5 on 2025-08-19 18:40

import django.db.models.deletion
import judge.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('challenge_body', models.TextField()),
                ('constraints', models.TextField()),
                ('input_instruction', models.TextField()),
                ('output_instruction', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('solution_file', models.FileField(upload_to=judge.models.path_for_solution)),
                ('outcome', models.BooleanField(editable=False)),
                ('number_of_test_cases', models.IntegerField(default=0, editable=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='judge.challenge')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution', to='judge.language')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('test_case', models.FileField(upload_to=judge.models.path_for_testcase, validators=[judge.models.validate_file_type])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='judge.challenge')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case', to='judge.language')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('language', 'challenge'), name='one-test-case-per-language-per-challenge')],
            },
        ),
    ]
