name: Pull Request Notification
on:
 pull_request:
  types: [opened]
jobs:
 mail:
  environment: Gavel
  runs-on: ubuntu-latest
  steps:
   - name: Pull Request Email
     uses: dawidd6/action-send-mail@v6
     with:
      server_address: smtp.gmail.com
      server_port: 587
      username: jashupadhyay.java@gmail.com
      password: ${{secrets.smtp}}
      from: Team Gavel <jashupadhyay.java@gmail.com>
      to: jashupadhyay.java@gmail.com
      subject: Pull Request For Gavel Opened
      body: |
       Greetings,
       Sender Detail JSON Given Below
       ${{(toJSON(github.event))['sender']}}
       Regards,
       Team Gavel
